version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: exampledb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress-ai-extension:/var/www/html/wp-content/plugins/kangaroo-detector
    depends_on:
      - exampledb
      - flask-app
    networks:
      - my-network

  exampledb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wordpress-ai-extension:/app
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
